### PR TITLE
Added SVG badges

### PR DESCRIPTION
**Pull request by haukex**
I recently released [`Badge::Simple`](https://metacpan.org/pod/Badge::Simple) ([haukex/Badge-Simple](https://github.com/haukex/Badge-Simple#badge-simple)). If you like this module, here is a patch that adds `WWW::CPANTS::Web::Util::BadgeSVG` (modeled after `WWW::CPANTS::Web::Util::Badge`) to provide SVG badges.

### CODE REVIEW

**Comment by charsbar** [comment]
Cool! Thanks.

**Comment by charsbar** [comment]
Deployed: https://cpants.cpanauthors.org/author/haukex.svg

**Comment by haukex** [comment]
Excellent, thank you very much!

**Comment by haukex** [comment]
Wrote about it on PerlMonks: <https://www.perlmonks.org/?node_id=1225536>

**Pull request merged**
